version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: orca
      POSTGRES_PASSWORD: still-cool
    ports:
      - 5432:5432
  
  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 5444:8080